### ISSUE TITLE
GitError: mpp update-ref: fatal: 77b58369658b739e5c99b6a6876809e073086dcf^0: not a valid SHA1

### ISSUE THREAD

**Issue by GitMAGI** [rockchip-linux/mpp#134]
Hi i'm trying to get the source for the chip 3328. 
When I execute sync I got the error.
This is the complete stack i got:

warning: project 'repo' branch 'stable' is not signed
warning: Skipped upgrade to unverified version
error: Cannot fetch mpp (GitError: mpp update-ref: fatal: 77b58369658b739e5c99b6a6876809e073086dcf^0: not a valid SHA1
)
Exception in thread Thread-53:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/developer-admin/rk3328-workspace/rockchip/repo/subcmds/sync.py", line 289, in _FetchProjectList
    success = self._FetchHelper(opt, project, *args, **kwargs)
  File "/home/developer-admin/rk3328-workspace/rockchip/repo/subcmds/sync.py", line 333, in _FetchHelper
    clone_filter=clone_filter)
  File "/home/developer-admin/rk3328-workspace/rockchip/repo/project.py", line 1469, in Sync_NetworkHalf
    self._InitMRef()
  File "/home/developer-admin/rk3328-workspace/rockchip/repo/project.py", line 2643, in _InitMRef
    self._InitAnyMRef(R_M + self.manifest.branch)
  File "/home/developer-admin/rk3328-workspace/rockchip/repo/project.py", line 2655, in _InitAnyMRef
    self.bare_git.UpdateRef(ref, dst, message=msg, detach=True)
  File "/home/developer-admin/rk3328-workspace/rockchip/repo/project.py", line 2969, in UpdateRef
    self.update_ref(*cmdv)
  File "/home/developer-admin/rk3328-workspace/rockchip/repo/project.py", line 3038, in runner
    (self._project.name, name, p.stderr))
GitError: mpp update-ref: fatal: 77b58369658b739e5c99b6a6876809e073086dcf^0: not a valid SHA1

Checking out projects:  42% (11/26) audioservicefatal: failed to unpack tree object HEAD
error: Cannot checkout gstreamer-rockchip: GitError: Cannot initialize work tree for gstreamer-rockchip
Traceback (most recent call last):
  File "/home/developer-admin/rk3328-workspace/rockchip/repo/main.py", line 530, in <module>
    _Main(sys.argv[1:])
  File "/home/developer-admin/rk3328-workspace/rockchip/repo/main.py", line 505, in _Main
    result = run()
  File "/home/developer-admin/rk3328-workspace/rockchip/repo/main.py", line 498, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/home/developer-admin/rk3328-workspace/rockchip/repo/main.py", line 201, in _Run
    result = cmd.Execute(copts, cargs)
  File "/home/developer-admin/rk3328-workspace/rockchip/repo/subcmds/sync.py", line 994, in Execute
    self._Checkout(all_projects, opt)
  File "/home/developer-admin/rk3328-workspace/rockchip/repo/subcmds/sync.py", line 553, in _Checkout
    self._CheckoutWorker(**kwargs)
  File "/home/developer-admin/rk3328-workspace/rockchip/repo/subcmds/sync.py", line 435, in _CheckoutWorker
    return self._CheckoutOne(opt, project, *args, **kwargs)
  File "/home/developer-admin/rk3328-workspace/rockchip/repo/subcmds/sync.py", line 469, in _CheckoutOne
    project.Sync_LocalHalf(syncbuf, force_sync=opt.force_sync)
  File "/home/developer-admin/rk3328-workspace/rockchip/repo/project.py", line 1532, in Sync_LocalHalf
    self._InitWorkTree(force_sync=force_sync, submodules=submodules)
  File "/home/developer-admin/rk3328-workspace/rockchip/repo/project.py", line 2776, in _InitWorkTree
    raise GitError('Cannot initialize work tree for ' + self.name)
error.GitError: Cannot initialize work tree for gstreamer-rockchip

**Comment by JeffyCN** [comment]
Looks like the manifest is outdated.
We don't actually using the github manifest, @eddiecailinux @Caesar-github
