### ISSUE TITLE
RK3399 mpp_enc线程崩溃

### ISSUE THREAD

**Issue by imxys** [rockchip-linux/mpp#203]
我是将github [另一个mpp项目](https://github.com/HermanChen/mpp.git) 的代码复制到rk3399项目来编译的mpp库
使用场景类似于编码器 创建，使用再销毁，然后重新创建使用，然后在另一个线程调用 put_frame()时候发生崩溃了
麻烦帮忙看看有什么可能会处刑这个问题？因为是Mpp库内部线程，我不知道调用什么接口会影响到这里

```shell
Thread 1 (Thread 0x7e7ffff1c0 (LWP 588)):
#0  mpp_data_sum_v2 (p=0x0)
---Type <return> to continue, or q <return> to quit---
    at /media/xys/ssdext4/rk3399_linux_release/buildroot/output/rockchip_rk3399/build/mpp-release/mpp/codec/rc/rc_base.cpp:129
#1  0x0000007f54b65164 in check_re_enc (ctx=ctx@entry=0x7ebc000900, 
    cfg=cfg@entry=0x7efc02a628)
    at /media/xys/ssdext4/rk3399_linux_release/buildroot/output/rockchip_rk3399/build/mpp-release/mpp/codec/rc/rc_model_v2.c:1085
#2  0x0000007f54b65e78 in rc_model_v2_check_reenc (ctx=0x7ebc000900, 
    task=0x7efc02a588)
    at /media/xys/ssdext4/rk3399_linux_release/buildroot/output/rockchip_rk3399/build/mpp-release/mpp/codec/rc/rc_model_v2.c:1443
#3  0x0000007f54ae0bbc in mpp_enc_normal (task=0x7e7fffe6f8, mpp=0x7efc01d750)
    at /media/xys/ssdext4/rk3399_linux_release/buildroot/output/rockchip_rk3399/build/mpp-release/mpp/codec/mpp_enc_impl.cpp:1271
#4  try_proc_normal_task (task=0x7e7fffe6f8, enc=0x7efc02a520)
    at /media/xys/ssdext4/rk3399_linux_release/buildroot/output/rockchip_rk3399/build/mpp-release/mpp/codec/mpp_enc_impl.cpp:1821
#5  mpp_enc_thread (data=0x7efc01d750)
    at /media/xys/ssdext4/rk3399_linux_release/buildroot/output/rockchip_rk3399/build/mpp-release/mpp/codec/mpp_enc_impl.cpp:1976
#6  0x0000007f79eb97e4 in start_thread () from /lib/libpthread.so.0
#7  0x0000007f79e126bc in ?? () from /lib/libc.so.6
```

**Comment by imxys** [comment]
问题解决，可能与编码器虽然销毁重建，但是MppEncCfg对象我保留用作下一次配置有关。
现在MppEncCfg创建后配置编码器，然后立刻销毁，暂时没有出现崩溃。
